// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Infrastructure.Data;

namespace Travel.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<decimal>("AuthorsId")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("BooksIsbn")
                        .HasColumnType("numeric(13,0)");

                    b.HasKey("AuthorsId", "BooksIsbn");

                    b.HasIndex("BooksIsbn");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1000000000m,
                            BooksIsbn = 9780060114183m
                        },
                        new
                        {
                            AuthorsId = 1000000000m,
                            BooksIsbn = 9781400034710m
                        },
                        new
                        {
                            AuthorsId = 1000000001m,
                            BooksIsbn = 9780062930040m
                        },
                        new
                        {
                            AuthorsId = 1000000002m,
                            BooksIsbn = 9780062930040m
                        },
                        new
                        {
                            AuthorsId = 1000000003m,
                            BooksIsbn = 9780062930040m
                        });
                });

            modelBuilder.Entity("Travel.Infrastructure.Models.Author", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1000000000m,
                            FirstName = "Gabriel",
                            LastName = "Garcia Marquez"
                        },
                        new
                        {
                            Id = 1000000001m,
                            FirstName = "Cynthia",
                            LastName = "Hand"
                        },
                        new
                        {
                            Id = 1000000002m,
                            FirstName = "Brodi",
                            LastName = "Ashton"
                        },
                        new
                        {
                            Id = 1000000003m,
                            FirstName = "Jodi",
                            LastName = "Meadows"
                        });
                });

            modelBuilder.Entity("Travel.Infrastructure.Models.Book", b =>
                {
                    b.Property<decimal>("Isbn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(13,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<decimal>("EditorialId")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("Pages")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Isbn");

                    b.HasIndex("EditorialId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Isbn = 9780060114183m,
                            EditorialId = 1000000000m,
                            Pages = "504",
                            Synopsis = "A best seller and critical success in Latin America, Europe, and the United States, One Hundred Years of Solitude tells the story of the rise and fall, birth and death of teh mythical town of Macondo through the history of the Buendia family. It is a rich and billiant chronicle of life and death and the tragicomedy of man. In the noble, ridiculous, beautiful, and tawdry story of the Buendia family one sees all mankind, just as in the history, myths, growth, and decay of Macondo one sees all of Latin America.\nLove and lust, war and revolution, reiches and poverty, youth and senility--the variety of life, the endlessness fo death, the search for peace and truth--these, the universal themes, dominate the novel.Whether he is describing an affair of passion or the voracity of capitalism and the corruption of government, Garcia Marquez always writes with the simplicity, ease, and purity that are the mark fo a master.Inventive, amusing, magnetic, sad, alive with unforgettale men and women, and with a truth and understanding that strike the soul, One Hundred Years of Solitude is a masterpiece of the art of fiction.\n“synopsis” may belong to another edition of this title.",
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            Isbn = 9781400034710m,
                            EditorialId = 1000000001m,
                            Pages = "128",
                            Synopsis = "A man returns to the town where a baffling murder took place 27 years earlier, determined to get to the bottom of the story. Just hours after marrying the beautiful Angela Vicario, everyone agrees, Bayardo San Roman returned his bride in disgrace to her parents. Her distraught family forced her to name her first lover; and her twin brothers announced their intention to murder Santiago Nasar for dishonoring their sister.\nYet if everyone knew the murder was going to happen, why did no one intervene to stop it? The more that is learned, the less is understood, and as the story races to its inexplicable conclusion, an entire society--not just a pair of murderers—is put on trial.",
                            Title = "Chronicle of a Death Foretold"
                        },
                        new
                        {
                            Isbn = 9780062930040m,
                            EditorialId = 1000000002m,
                            Pages = "512",
                            Synopsis = "Long live the queen: The authors who brought you the New York Times bestselling My Lady Jane kick off an all-new historical trilogy with the classy, courtly tale of Mary, Queen of Scots.\nWelcome to Renaissance France, a place of poison and plots, of beauties and beasts, of mice and . . . queens?\nMary is the queen of Scotland and the jewel of the French court. Except when she’s a mouse. Yes, reader, Mary is an Eðian (shapeshifter) in a kingdom where Verities rule. It’s a secret that could cost her a head—or a tail.\nLuckily, Mary has a confidant in her betrothed, Francis. But things at the gilded court take a treacherous turn after the king meets a suspicious end. Thrust onto the throne, Mary and Francis face a viper’s nest of conspiracies, traps, and treason. And if Mary’s secret is revealed, heads are bound to roll.\nWith a royally clever sense of humor, Cynthia Hand, Brodi Ashton, and Jodi Meadows continue their campaign to turn history on its head in this YA fantasy that’s perfect for fans of A Gentleman’s Guide to Vice and Virtue.",
                            Title = "My Contrary Mary"
                        });
                });

            modelBuilder.Entity("Travel.Infrastructure.Models.Editorial", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("Headquarters")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Editorials");

                    b.HasData(
                        new
                        {
                            Id = 1000000000m,
                            Headquarters = "North",
                            Name = "Harper & Row"
                        },
                        new
                        {
                            Id = 1000000001m,
                            Headquarters = "Main",
                            Name = "Vintage"
                        },
                        new
                        {
                            Id = 1000000002m,
                            Headquarters = "South",
                            Name = "Harper Teen"
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("Travel.Infrastructure.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Infrastructure.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksIsbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Travel.Infrastructure.Models.Book", b =>
                {
                    b.HasOne("Travel.Infrastructure.Models.Editorial", "Editorial")
                        .WithMany("Books")
                        .HasForeignKey("EditorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("Travel.Infrastructure.Models.Editorial", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
